pipelineAccount:
  awsAccountId: 975050368328
  awsRegion: us-east-1

devAccount:
  awsAccountId: 992382736109
  awsRegion: us-east-1

prodAccount:
  awsAccountId: 975050168644
  awsRegion: us-east-1

dev:
  dataLocation: s3://dev-glue-data-992382736109-us-east-1

prod:
  dataLocation: s3://prod-glue-data-975050168644-us-east-1
